### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by MaximumViciousDeer** [inconspicuous-creations/Inconspicuous.Framework#2]
There seems to be a problem with the included examples. Both examples' main context views are missing their script: "The referenced script on this Behaviour is missing!"
Adding either Main- or CustomContextView with selected context set to either MainContext or TestContext does not fix the problem.

**Comment by yuhe00** [comment]
Sorry about this. The examples are outdated and broken. I removed them and uploaded a new project at https://github.com/inconspicuous-creations/Inconspicuous.Framework.Example.

**Comment by MaximumViciousDeer** [comment]
Thanks, I'll have a look!
